//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceReference1
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.CountWebServiceSoap")]
    public interface CountWebServiceSoap
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/FavoriteCount", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.FavoriteCountResponse> FavoriteCountAsync(ServiceReference1.FavoriteCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WatchListCount", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.WatchListCountResponse> WatchListCountAsync(ServiceReference1.WatchListCountRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/WatchedListCount", ReplyAction="*")]
        System.Threading.Tasks.Task<ServiceReference1.WatchedListCountResponse> WatchedListCountAsync(ServiceReference1.WatchedListCountRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FavoriteCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FavoriteCount", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.FavoriteCountRequestBody Body;
        
        public FavoriteCountRequest()
        {
        }
        
        public FavoriteCountRequest(ServiceReference1.FavoriteCountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FavoriteCountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public FavoriteCountRequestBody()
        {
        }
        
        public FavoriteCountRequestBody(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class FavoriteCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="FavoriteCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.FavoriteCountResponseBody Body;
        
        public FavoriteCountResponse()
        {
        }
        
        public FavoriteCountResponse(ServiceReference1.FavoriteCountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class FavoriteCountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int FavoriteCountResult;
        
        public FavoriteCountResponseBody()
        {
        }
        
        public FavoriteCountResponseBody(int FavoriteCountResult)
        {
            this.FavoriteCountResult = FavoriteCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WatchListCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WatchListCount", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.WatchListCountRequestBody Body;
        
        public WatchListCountRequest()
        {
        }
        
        public WatchListCountRequest(ServiceReference1.WatchListCountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WatchListCountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public WatchListCountRequestBody()
        {
        }
        
        public WatchListCountRequestBody(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WatchListCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WatchListCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.WatchListCountResponseBody Body;
        
        public WatchListCountResponse()
        {
        }
        
        public WatchListCountResponse(ServiceReference1.WatchListCountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WatchListCountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int WatchListCountResult;
        
        public WatchListCountResponseBody()
        {
        }
        
        public WatchListCountResponseBody(int WatchListCountResult)
        {
            this.WatchListCountResult = WatchListCountResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WatchedListCountRequest
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WatchedListCount", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.WatchedListCountRequestBody Body;
        
        public WatchedListCountRequest()
        {
        }
        
        public WatchedListCountRequest(ServiceReference1.WatchedListCountRequestBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WatchedListCountRequestBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string userId;
        
        public WatchedListCountRequestBody()
        {
        }
        
        public WatchedListCountRequestBody(string userId)
        {
            this.userId = userId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class WatchedListCountResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="WatchedListCountResponse", Namespace="http://tempuri.org/", Order=0)]
        public ServiceReference1.WatchedListCountResponseBody Body;
        
        public WatchedListCountResponse()
        {
        }
        
        public WatchedListCountResponse(ServiceReference1.WatchedListCountResponseBody Body)
        {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class WatchedListCountResponseBody
    {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int WatchedListCountResult;
        
        public WatchedListCountResponseBody()
        {
        }
        
        public WatchedListCountResponseBody(int WatchedListCountResult)
        {
            this.WatchedListCountResult = WatchedListCountResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public interface CountWebServiceSoapChannel : ServiceReference1.CountWebServiceSoap, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.2")]
    public partial class CountWebServiceSoapClient : System.ServiceModel.ClientBase<ServiceReference1.CountWebServiceSoap>, ServiceReference1.CountWebServiceSoap
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public CountWebServiceSoapClient(EndpointConfiguration endpointConfiguration) : 
                base(CountWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), CountWebServiceSoapClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountWebServiceSoapClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(CountWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountWebServiceSoapClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(CountWebServiceSoapClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public CountWebServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.FavoriteCountResponse> ServiceReference1.CountWebServiceSoap.FavoriteCountAsync(ServiceReference1.FavoriteCountRequest request)
        {
            return base.Channel.FavoriteCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.FavoriteCountResponse> FavoriteCountAsync(string userId)
        {
            ServiceReference1.FavoriteCountRequest inValue = new ServiceReference1.FavoriteCountRequest();
            inValue.Body = new ServiceReference1.FavoriteCountRequestBody();
            inValue.Body.userId = userId;
            return ((ServiceReference1.CountWebServiceSoap)(this)).FavoriteCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.WatchListCountResponse> ServiceReference1.CountWebServiceSoap.WatchListCountAsync(ServiceReference1.WatchListCountRequest request)
        {
            return base.Channel.WatchListCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WatchListCountResponse> WatchListCountAsync(string userId)
        {
            ServiceReference1.WatchListCountRequest inValue = new ServiceReference1.WatchListCountRequest();
            inValue.Body = new ServiceReference1.WatchListCountRequestBody();
            inValue.Body.userId = userId;
            return ((ServiceReference1.CountWebServiceSoap)(this)).WatchListCountAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceReference1.WatchedListCountResponse> ServiceReference1.CountWebServiceSoap.WatchedListCountAsync(ServiceReference1.WatchedListCountRequest request)
        {
            return base.Channel.WatchedListCountAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceReference1.WatchedListCountResponse> WatchedListCountAsync(string userId)
        {
            ServiceReference1.WatchedListCountRequest inValue = new ServiceReference1.WatchedListCountRequest();
            inValue.Body = new ServiceReference1.WatchedListCountRequestBody();
            inValue.Body.userId = userId;
            return ((ServiceReference1.CountWebServiceSoap)(this)).WatchedListCountAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CountWebServiceSoap))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                result.Security.Mode = System.ServiceModel.BasicHttpSecurityMode.Transport;
                return result;
            }
            if ((endpointConfiguration == EndpointConfiguration.CountWebServiceSoap12))
            {
                System.ServiceModel.Channels.CustomBinding result = new System.ServiceModel.Channels.CustomBinding();
                System.ServiceModel.Channels.TextMessageEncodingBindingElement textBindingElement = new System.ServiceModel.Channels.TextMessageEncodingBindingElement();
                textBindingElement.MessageVersion = System.ServiceModel.Channels.MessageVersion.CreateVersion(System.ServiceModel.EnvelopeVersion.Soap12, System.ServiceModel.Channels.AddressingVersion.None);
                result.Elements.Add(textBindingElement);
                System.ServiceModel.Channels.HttpsTransportBindingElement httpsBindingElement = new System.ServiceModel.Channels.HttpsTransportBindingElement();
                httpsBindingElement.AllowCookies = true;
                httpsBindingElement.MaxBufferSize = int.MaxValue;
                httpsBindingElement.MaxReceivedMessageSize = int.MaxValue;
                result.Elements.Add(httpsBindingElement);
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.CountWebServiceSoap))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44322/CountWebService.asmx");
            }
            if ((endpointConfiguration == EndpointConfiguration.CountWebServiceSoap12))
            {
                return new System.ServiceModel.EndpointAddress("https://localhost:44322/CountWebService.asmx");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        public enum EndpointConfiguration
        {
            
            CountWebServiceSoap,
            
            CountWebServiceSoap12,
        }
    }
}
